version: '3.8'

services:
  db:
    image: postgres:13
    container_name: openproject-db
    environment:
      POSTGRES_USER: openproject
      POSTGRES_PASSWORD: openproject
      POSTGRES_DB: openproject
    volumes:
      - openproject_db_data:/var/lib/postgresql/data
    networks:
      - openproject
      - traefik_reverse_proxy
    restart: always

  openproject:
    image: openproject/community:latest
    container_name: openproject
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://openproject:openproject@db/openproject
      SECRET_KEY_BASE: supersecretkeybase
    volumes:
      - openproject_data:/var/openproject/assets
    ports:
      - "8080:80"
    networks:
      - openproject
      - traefik_reverse_proxy
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openproject.rule=Host(`openproject.elmakchi.ir`)"
      - "traefik.http.routers.openproject.entrypoints=websecure"
      - "traefik.http.routers.openproject.tls.certresolver=myresolver"
      - "traefik.http.services.openproject.loadbalancer.server.port=80"

volumes:
  openproject_db_data:
  openproject_data:

networks:
  openproject:
    driver: bridge
  traefik_reverse_proxy:
    external: true
