version: '3'

services:
  fluentd:
    image: fluent/fluentd:v1.16-debian
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/fluentd/log
    networks:
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fluentd.rule=Host(`fluentd.elmakchi.ir`)"
      - "traefik.http.routers.fluentd.entrypoints=websecure"
      - "traefik.http.routers.fluentd.tls.certresolver=myresolver"
      - "traefik.http.services.fluentd.loadbalancer.server.port=80"
    ports:
      - "9880:9880"            # 👈 برای in_http
      - "24224:24224"          # 👈 برای in_forward
      - "24224:24224/udp"
   
networks:
  traefik_reverse_proxy:
    external: true

volumes:
  logs: