version: "3.3"
services:
  poste.io:
    image: analogic/poste.io
    network_mode: host
    environment:
      - TZ=Europe/Prague
    volumes:
      - ./data:/data
    
    hostname: mail.example.com
    tty: true
    restart: always
    networks:
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.posteio.rule=Host(`posteio.elmakchi.ir`)"
      - "traefik.http.routers.posteio.entrypoints=websecure"
      - "traefik.http.routers.posteio.tls.certresolver=myresolver"
      - "traefik.http.services.posteio.loadbalancer.server.port=8080"

networks:
  traefik_reverse_proxy:
    external: true