version: '3.8'

services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    restart: unless-stopped
    environment:
      - TZ=Asia/Tehran
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./bind9/etc/bind:/etc/bind
      - ./bind9/var/cache/bind:/var/cache/bind
      - ./bind9/var/lib/bind:/var/lib/bind

  webmin:
    image: sameersbn/webmin:latest
    container_name: webmin
    restart: unless-stopped
    environment:
      - WEBMIN_ENABLED_MODULES=bind8
    ports:
      - "10000:10000"
    volumes:
      - ./webmin/etc/webmin:/etc/webmin
      - ./bind9/etc/bind:/etc/bind   # اتصال به کانفیگ‌های BIND برای مدیریت
    networks:
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webmin.rule=Host(`webmin.elmakchi.ir`)"
      - "traefik.http.routers.webmin.entrypoints=websecure"
      - "traefik.http.routers.webmin.tls.certresolver=myresolver"
      - "traefik.http.services.webmin.loadbalancer.server.port=10000"

networks:
  traefik_reverse_proxy:
    external: true
