version: "3.8"

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_SERVER_MODE=true
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/file
    networks:
      - vault_net
      - traefik_reverse_proxy
    command: "server"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.elmakchi.ir`)"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.routers.vault.tls.certresolver=myresolver"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"

networks:
  vault_net:
    driver: bridge
  traefik_reverse_proxy:
    external: true

volumes:
  vault_data:
