version: '3.8'

services:
  adminmongo:
    image: mrvautin/adminmongo
    container_name: adminmongo
    restart: always
    ports:
      - "8081:1234"
    environment:
      - HOST=0.0.0.0
    volumes:
      - adminmongo_data:/app/data
    networks:
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis.rule=Host(`redis.elmakchi.ir`)"
      - "traefik.http.routers.redis.entrypoints=websecure"
      - "traefik.http.routers.redis.tls.certresolver=myresolver"
      - "traefik.http.services.redis.loadbalancer.server.port=80"

networks:
  traefik_reverse_proxy:
    external: true

volumes:
  adminmongo_data: