version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=supersecret
      - DOCKER_INFLUXDB_INIT_ORG=elmakchi
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - internal_network
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.elmakchi.ir`)"
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.http.routers.influxdb.tls.certresolver=myresolver"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"

volumes:
  influxdb_data:

networks:
  traefik_reverse_proxy:
    external: true
  internal_network:
    driver: bridge
